# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.9]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install '.[dev]'
    - uses: jpetrucciani/black-check@master
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --max-complexity=10 --max-line-length=88 --ignore E203,E501,W503,E701 --statistics
    - name: Run Bandit
      uses: jpetrucciani/bandit-check@master
      with:
        path: 'arrnounced'
    - name: Run unit tests
      run: |
        ./run_tests.py
